# Generated by Django 4.0.2 on 2022-02-18 13:40

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=tinymce.models.HTMLField(max_length=300),
        ),
    ]
