# Generated by Django 4.0.4 on 2022-05-21 13:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_alter_product_short_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrdetPlaced',
            new_name='OrderPlaced',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop')], max_length=10),
        ),
    ]
