# Generated by Django 4.0.4 on 2022-05-29 18:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Verification',
        ),
    ]
