# Generated by Django 4.0.4 on 2022-06-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('1', 'Mobile'), ('2', 'Laptop'), ('3', 'Electronic Accessories')], max_length=10),
        ),
    ]
