# Generated by Django 4.0.4 on 2022-06-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('Mobile', 'Mobile'), ('Laptop', 'Laptop'), ('ElectronicAccessories', 'Electronic Accessories')], max_length=30),
        ),
    ]
