# Generated by Django 4.0.4 on 2022-06-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Mobile', 'Mobile'), ('Laptop', 'Laptop'), ('ElectronicAccessories', 'Electronic Accessories')], max_length=30),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
